CREATE TYPE status AS ENUM ('waiting', 'skipped', 'performed');

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	phone VARCHAR(20) NOT NULL UNIQUE,
	login VARCHAR(50) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	registered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	last_login_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE shcedule (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	procedure VARCHAR (50) NOT NULL,
	time_to_do TIMESTAMP WITH ZONE,
	proc_status status NOT NULL DEFAULT 'waiting', 

	CONSTRAINT fk_users_id
		FOREIGN KEY (user_id)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);

CREATE TABLE protocols (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	protocol json NOT NULL DEFAULT '{}',
	uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

	CONSTRAINT fk_users_id
		FOREIGN KEY (user_id)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);